### ISSUE TITLE
Is the link to the design software still accurate?

### ISSUE THREAD

**Issue by tommythorn** [RISCV-on-Microsemi-FPGA/MPF300T-PolarFire-Eval-Kit#6]
The README.md says "Details of the features of PolarFire Evaluation kit are available here."
but following "here" brings us to a page that states

"Microsemi's PolarFire FPGA Family  has a dedicated software release Libero SoC PolarFire, it is not supported in Libero SoC."

That's does that mean the "here" link is out of date?

(OT: is it correctly understood that there is no free-of-charge design software for any of the available PolarFire dev kits?  It seems only MPF300TS kits are available and the Libero SoC PolarFire Silver license only supports MPF100T.  How does that make sense?)

**Comment by CLappin** [comment]
Hi Tommy, 

Thank you for bringing  this to our attention that link is indeed out of date. I will update the readme.md file to point to the correct version of Libero soon.

With regards to you licence query, each PolarFire Development Kit comes with a one year Gold license. In the Development Kit box there should be a letter which has a Software ID which allows you to access this license. 

If you have any issues activating your new software license please contact our technical support teams via http://soc.microsemi.com/mycase or soc_tech@microsemi.com

Apologies for the delayed response, 
Ciaran

**Comment by AntonKrug** [comment]
Got the content of link updated? Does this need to be kept as an opened issue?

**Comment by CLappin** [comment]
Hi Anton, 

Yes of link was updated in the new PolarFire Eval kit page which has been relocated to [here](https://github.com/RISCV-on-Microsemi-FPGA/PolarFire-Eval-Kit) .

A list of all the software need to run a MIV processor can be found [here](https://github.com/RISCV-on-Microsemi-FPGA/Design-Tools).

Thanks,
Ciaran

**Comment by AntonKrug** [comment]
Thanks Ciaran.

Should then this repository market in the readme as obsolete and linking the https://github.com/RISCV-on-Microsemi-FPGA/PolarFire-Eval-Kit as the authoritative, while mentioning it in the newer repository that it is superseding this repository to completely rule out any ambiguity? Because I don't think visitors will be looking through the issues to see if the repository was relocated or not.
